# -*- mode: python ; coding: utf-8 -*-
"""
PyInstaller Spec File for ZZZ Mod Fixer 
Character Data Separation - Single Executable Build

This spec file packages the modular character data system
into a single executable with all character modules embedded.
"""

block_cipher = None

# List all character modules for explicit inclusion (Telah diselaraskan dengan v2.8)
character_modules = [
    'PlayerCharacterPYData.Alice',
    'PlayerCharacterPYData.AliceSummer',
    'PlayerCharacterPYData.Anby',
    'PlayerCharacterPYData.Anton',
    'PlayerCharacterPYData.Aria',
    'PlayerCharacterPYData.AriaAgent',
    'PlayerCharacterPYData.AriaAgentDiscordantNote',
    'PlayerCharacterPYData.AriaDiscordantNote',
    'PlayerCharacterPYData.AstraChandelier',
    'PlayerCharacterPYData.AstraYao',
    'PlayerCharacterPYData.Banyue',
    'PlayerCharacterPYData.Belle',
    'PlayerCharacterPYData.BelleBrillianceOfStars',
    'PlayerCharacterPYData.BelleSummer',
    'PlayerCharacterPYData.BelleTemple',
    'PlayerCharacterPYData.Ben',
    'PlayerCharacterPYData.Billy',
    'PlayerCharacterPYData.Burnice',
    'PlayerCharacterPYData.Caesar',
    'PlayerCharacterPYData.Cissia',
    'PlayerCharacterPYData.Corin',
    'PlayerCharacterPYData.Dialyn',
    'PlayerCharacterPYData.Ellen',
    'PlayerCharacterPYData.EllenCampus',
    'PlayerCharacterPYData.Evelyn',
    'PlayerCharacterPYData.Grace',
    'PlayerCharacterPYData.Harumasa',
    'PlayerCharacterPYData.Hugo',
    'PlayerCharacterPYData.JaneDoe',
    'PlayerCharacterPYData.JaneDoeNocturneOfLight',
    'PlayerCharacterPYData.JuFufu',
    'PlayerCharacterPYData.Koleda',
    'PlayerCharacterPYData.Lighter',
    'PlayerCharacterPYData.Lucia',
    'PlayerCharacterPYData.Lucy',
    'PlayerCharacterPYData.Lycaon',
    'PlayerCharacterPYData.Manato',
    'PlayerCharacterPYData.ManatoWhiteHeartSilhouette',
    'PlayerCharacterPYData.Miyabi',
    'PlayerCharacterPYData.MiyabiDignifiedBlossom',
    'PlayerCharacterPYData.NangongYu',
    'PlayerCharacterPYData.NangongYuRhapsodyMuse',
    'PlayerCharacterPYData.Nekomata',
    'PlayerCharacterPYData.Nicole',
    'PlayerCharacterPYData.NicoleCutie',
    'PlayerCharacterPYData.Norma',
    'PlayerCharacterPYData.Orphie',
    'PlayerCharacterPYData.PanYinhu',
    'PlayerCharacterPYData.PanYinhuCulinaryJewel',
    'PlayerCharacterPYData.Piper',
    'PlayerCharacterPYData.Promeia',
    'PlayerCharacterPYData.Pulchra',
    'PlayerCharacterPYData.Pyrois',
    'PlayerCharacterPYData.Qingyi',
    'PlayerCharacterPYData.Rina',
    'PlayerCharacterPYData.Seed',
    'PlayerCharacterPYData.Seth',
    'PlayerCharacterPYData.Soldier0',
    'PlayerCharacterPYData.Soldier11',
    'PlayerCharacterPYData.Soukaku',
    'PlayerCharacterPYData.StarlightBilly',
    'PlayerCharacterPYData.Sunna',
    'PlayerCharacterPYData.SunnaAfternoonTeaBreak',
    'PlayerCharacterPYData.Trigger',
    'PlayerCharacterPYData.Velina',
    'PlayerCharacterPYData.VelinaShadeOfLeisure',
    'PlayerCharacterPYData.Vivian',
    'PlayerCharacterPYData.VivianSummer',
    'PlayerCharacterPYData.Wise',
    'PlayerCharacterPYData.WiseOathOfSkies',
    'PlayerCharacterPYData.WiseSummer',
    'PlayerCharacterPYData.WiseTemple',
    'PlayerCharacterPYData.Yanagi',
    'PlayerCharacterPYData.YeShunguang',
    'PlayerCharacterPYData.YeShunguangSword',
    'PlayerCharacterPYData.YeShunguangSwordUlt',
    'PlayerCharacterPYData.YeShunguangTouchOfDawnlight',
    'PlayerCharacterPYData.YeShunguangUlt',
    'PlayerCharacterPYData.Yidhari',
    'PlayerCharacterPYData.Yixuan',
    'PlayerCharacterPYData.YixuanTrailsOfInk',
    'PlayerCharacterPYData.Yuzuha',
    'PlayerCharacterPYData.YuzuhaSummer',
    'PlayerCharacterPYData.Zhao',
    'PlayerCharacterPYData.ZhuYuan',
]

a = Analysis(
    ['zzz-mod-fixer.py'],
    pathex=[],
    binaries=[],
    datas=[
        # Include all character module files
        ('Assets/PlayerCharacterPYData/*.py', 'Assets/PlayerCharacterPYData'),
    ],
    hiddenimports=character_modules,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='zzz-mod-fixer-v3.0',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)